### ISSUE TITLE
Display reason for not crafting queue

### ISSUE THREAD

**Issue by mackenza** [Dolgubon/DolgubonsLazySetCrafter#1]
When there are items in the queue and I go to a crafting station, sometimes it doesn't craft and there is no indication of why.

It could be various reasons, like lack of mats (materials, enahncements, traits), or lack of knowledge (of a trait or motif) or being at the wrong crafting station for a set. I am sure there are other reasons.

It would be nice to have some sort of feedback as to why.

**Comment by Dolgubon** [comment]
Mostly implemented. Being at the wrong crafting station is the only one which isn't, but I don't think I'll be adding that, as I don't think there's a good way to do so.
